[package]
name = "stepper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv-rt = "0.6.1"
panic-halt = "0.2.0"

[profile.release]
codegen-units = 1
debug = true
lto = true
